# Generated by Django 4.2.4 on 2023-12-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registerno', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
